# Generated by Django 4.2.1 on 2024-05-08 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='')),
                ('iname', models.CharField(max_length=30)),
                ('rate', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('prate', models.IntegerField()),
                ('pqty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('adrs', models.CharField(max_length=200)),
                ('eml', models.CharField(max_length=30)),
                ('phn', models.CharField(max_length=10)),
                ('pas', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('oadrs', models.CharField(default='', max_length=200)),
                ('ono', models.CharField(default='', max_length=10)),
                ('odate', models.DateField()),
                ('ddate', models.DateField(default=None)),
                ('tqty', models.IntegerField(default=1)),
                ('frate', models.IntegerField(default=1)),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cqty', models.IntegerField(default=1)),
                ('trate', models.IntegerField()),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
