# Generated by Django 4.2.1 on 2026-02-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='utype',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
