# Generated by Django 4.2.1 on 2026-02-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_utype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='utype',
            field=models.CharField(max_length=30),
        ),
    ]
